In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))
def identity_function(x):
    return x

In [3]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = np.dot(A,B)
print(C)

[[19 22]
 [43 50]]


In [4]:
np.ndim(A)

2

In [5]:
np.shape(B)

(2, 2)

In [6]:
np.size(C)

4

In [7]:
#此為兩層神經網路
L1 = np.array([1,2])
X = np.array([[1,3,5],[2,4,6]])
L2 = np.dot(L1,X) #乘積
print(L2)

[ 5 11 17]


In [8]:
B = np.array([1,2,3])#權重
L2_B = L2 + B
print(L2_B)
L2S = sigmoid(L2_B)
print(L2S)

[ 6 13 20]
[0.99752738 0.99999774 1.        ]


In [9]:
Y = np.array([[1,2],[3,4],[5,6]])#此為第三層神經網路
print(Y.shape)
L3 = np.dot(L2_B,Y)

print(L3)

(3, 2)
[145 184]


In [10]:
B = np.array([1,2])#權重
L3_B = L3 + B
print(L3_B)
L3S = sigmoid(L3_B)
print(L3S)

[146 186]
[1. 1.]


In [11]:
Z = identity_function(L3S)
print(Z)

[1. 1.]
